version: 2.1

orbs:
  sonarqube: sonarsource/sonarqube@1.2.1
  nexus: sonatype/nexus-deploy@1.1.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      # Install Node.js and NPM
      - run:
          name: Install Node.Js and npm
          command: |
            url -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
      # Install ESLint and run code analysis
      - run:
          name: Run ESLint
          command: |
            npm install -g eslint
            eslint common-app/
      - run: ./gradlew build
      - run:
          name: Upload Artifact to Nexus
          command: nexus/upload
          environment:
            NEXUS_URL: ""
            NEXUS_REPOSITORY: ""
            NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
            NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"

workflows:
  build-and-deploy:
    jobs:
      -build:
        context:
          - ci-secrets